name: GitHub Pages

on:
  push:
    branches:
      - dev

defaults:
  run:
    shell: bash
    working-directory: repo

jobs:
  container-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies and build
        run: |
          npm i -g pnpm
          pnpm install
          pnpm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
